# Generated by Django 5.2.5 on 2025-10-26 04:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_site", "0003_adminuser_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_name",
                    models.CharField(
                        help_text="Official Hospital Name", max_length=500
                    ),
                ),
                ("address", models.TextField(help_text="Primary hospital address")),
                (
                    "license_id",
                    models.CharField(
                        help_text="Unique National License ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "license_document",
                    models.FileField(
                        help_text="Upload mock license document",
                        upload_to="hospital_licenses/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
                "db_table": "admin_hospitals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="adminuser",
            name="hospital_registration_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_email_domain",
                        message="Email must be from a @*.gov.ph domain",
                        regex="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]*\\.gov\\.ph$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_users",
                to="admin_site.hospital",
            ),
        ),
    ]
