# Generated by Django 5.2.5 on 2025-10-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_site",
            "0004_hospital_adminuser_hospital_registration_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
