# Generated by Django 5.2.5 on 2025-10-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_patientassignment_consultationnotes"),
        ("users", "0009_update_profile_picture_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuemanagement",
            name="department",
            field=models.CharField(
                choices=[
                    ("OPD", "Out Patient Department"),
                    ("Pharmacy", "Pharmacy"),
                    ("Appointment", "Appointment"),
                ],
                help_text="Department for which the queue is managed.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="QueueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Out Patient Department"),
                            ("Billing", "Billing"),
                            ("Pharmacy", "Pharmacy"),
                            ("Appointment", "Appointment"),
                        ],
                        help_text="Department for which status is tracked",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the queue is currently open for new patients",
                    ),
                ),
                (
                    "current_serving",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Queue number currently being served",
                        null=True,
                    ),
                ),
                (
                    "total_waiting",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of patients currently waiting",
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated wait time for new patients",
                        null=True,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        default="Queue Closed",
                        help_text="Current status message displayed to patients",
                        max_length=200,
                    ),
                ),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the status",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Status",
                "verbose_name_plural": "Queue Statuses",
                "db_table": "queue_status",
            },
        ),
        migrations.CreateModel(
            name="QueueStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Out Patient Department"),
                            ("Billing", "Billing"),
                            ("Pharmacy", "Pharmacy"),
                            ("Appointment", "Appointment"),
                        ],
                        help_text="Department for which status changed",
                        max_length=100,
                    ),
                ),
                (
                    "previous_status",
                    models.BooleanField(help_text="Previous queue open/closed status"),
                ),
                (
                    "new_status",
                    models.BooleanField(help_text="New queue open/closed status"),
                ),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("schedule", "Scheduled Time"),
                            ("manual", "Manual Override"),
                            ("system", "System Update"),
                        ],
                        help_text="Reason for status change",
                        max_length=50,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the status change"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Status Log",
                "verbose_name_plural": "Queue Status Logs",
                "db_table": "queue_status_logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Out Patient Department"),
                            ("Billing", "Billing"),
                            ("Pharmacy", "Pharmacy"),
                            ("Appointment", "Appointment"),
                        ],
                        help_text="Department for which the schedule is set",
                        max_length=100,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Time when queue should open"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Time when queue should close"),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="List of days when queue is active (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is currently active",
                    ),
                ),
                (
                    "manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="Manual override by nurse (overrides time-based activation)",
                    ),
                ),
                (
                    "override_status",
                    models.CharField(
                        choices=[
                            ("enabled", "Manually Enabled"),
                            ("disabled", "Manually Disabled"),
                            ("auto", "Automatic"),
                        ],
                        default="auto",
                        help_text="Current override status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        help_text="Nurse who set the schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_schedules",
                        to="users.nurseprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Schedule",
                "verbose_name_plural": "Queue Schedules",
                "db_table": "queue_schedules",
                "ordering": ["-updated_at"],
                "unique_together": {("department", "nurse")},
            },
        ),
    ]
