# Generated by Django 5.2.5 on 2025-10-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_alter_queuemanagement_department_queuestatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuestatus",
            name="current_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently active schedule for this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operations.queueschedule",
            ),
        ),
    ]
