# Generated by Django 4.2.7 on 2025-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_queuestatus_current_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentmanagement",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for cancellation.", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointmentmanagement",
            name="reschedule_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rescheduling.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("rescheduled", "Rescheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
