# Generated by Django 4.2.16 on 2025-10-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_add_reschedule_cancel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='websocket', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the notification was delivered.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of delivery attempts.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the notification was sent.', null=True),
        ),
    ]
