# Generated by Django 4.2.16 on 2025-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_notification_channel_notification_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemanagement',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the queue started.', null=True),
        ),
    ]
