# Generated by Django 5.2.5 on 2025-10-19 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_queuemanagement_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityqueue',
            options={'ordering': ['enqueue_time', 'priority_position', 'created_at'], 'verbose_name': 'Priority Queue', 'verbose_name_plural': 'Priority Queues'},
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='enqueue_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the patient was added to the priority queue.'),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the priority processing finished.', null=True),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the priority processing started.', null=True),
        ),
        migrations.AddField(
            model_name='priorityqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='priorityqueue',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_queue', to='operations.appointmentmanagement'),
        ),
        migrations.AlterField(
            model_name='priorityqueue',
            name='priority_level',
            field=models.CharField(choices=[('pwd', 'Person With Disability'), ('pregnant', 'Pregnant'), ('senior', 'Senior Citizen'), ('with_child', 'Accompanying a Child')], default='senior', help_text='Priority level of the patient in the queue.', max_length=50),
        ),
    ]
