# Generated by Django 5.2.5 on 2025-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_priorityqueue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityqueue',
            name='department',
            field=models.CharField(choices=[('OPD', 'Out Patient Department'), ('Pharmacy', 'Pharmacy'), ('Appointment', 'Appointment')], default='OPD', help_text='Department for which the queue is managed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='priorityqueue',
            name='queue_number',
            field=models.PositiveIntegerField(help_text='Queue number for the priority patient.'),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='queue_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='queueschedule',
            name='department',
            field=models.CharField(choices=[('OPD', 'Out Patient Department'), ('Pharmacy', 'Pharmacy'), ('Appointment', 'Appointment')], help_text='Department for which the schedule is set', max_length=100),
        ),
        migrations.AlterField(
            model_name='queuestatus',
            name='department',
            field=models.CharField(choices=[('OPD', 'Out Patient Department'), ('Pharmacy', 'Pharmacy'), ('Appointment', 'Appointment')], help_text='Department for which status is tracked', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='queuestatuslog',
            name='department',
            field=models.CharField(choices=[('OPD', 'Out Patient Department'), ('Pharmacy', 'Pharmacy'), ('Appointment', 'Appointment')], help_text='Department for which status changed', max_length=100),
        ),
    ]
