# Generated by Django 5.2.5 on 2025-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_priorityqueue_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemanagement',
            name='daily_sequence_number',
            field=models.PositiveIntegerField(default=0, help_text='Sequential number for this patient for the day.'),
        ),
        migrations.AlterField(
            model_name='priorityqueue',
            name='queue_number',
            field=models.PositiveIntegerField(help_text='Queue number for the priority patient.', unique=True),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='queue_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
