# Generated by Django 5.2.5 on 2025-10-25 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0016_dailysequencecounter"),
        ("users", "0011_alter_user_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("export", "Export"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("query_params", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive Access Log",
                "verbose_name_plural": "Archive Access Logs",
                "db_table": "archive_access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientAssessmentArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_type", models.CharField(blank=True, max_length=100)),
                ("medical_condition", models.CharField(blank=True, max_length=200)),
                ("medical_history_summary", models.TextField(blank=True)),
                (
                    "assessment_data",
                    models.JSONField(
                        default=dict,
                        help_text="Complete patient assessment data (unencrypted copy for development)",
                    ),
                ),
                (
                    "encrypted_assessment_data",
                    models.TextField(
                        blank=True, help_text="Base64 encoded encrypted assessment data"
                    ),
                ),
                (
                    "diagnostics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Relevant diagnostic information",
                    ),
                ),
                ("last_assessed_at", models.DateTimeField(blank=True, null=True)),
                ("hospital_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="users.patientprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Assessment Archive",
                "verbose_name_plural": "Patient Assessment Archives",
                "db_table": "patient_assessment_archives",
                "ordering": ["-last_assessed_at", "-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="DailySequenceCounter",
        ),
        migrations.RemoveField(
            model_name="queuemanagement",
            name="daily_sequence_number",
        ),
        migrations.AddField(
            model_name="archiveaccesslog",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="operations.patientassessmentarchive",
            ),
        ),
    ]
