# Generated by Django 5.2.5 on 2025-10-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_archiveaccesslog_patientassessmentarchive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveaccesslog",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="operations.patientassessmentarchive",
            ),
        ),
    ]
