# Generated by Django 4.2.7 on 2025-10-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0019_mfachallenge_securekey_securetransmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentmanagement",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentmanagement",
            name="consultation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentmanagement",
            name="consultation_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("checked_in", "Checked In"),
                    ("in_progress", "In Progress"),
                    ("rescheduled", "Rescheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]