# Generated by Django 5.2.5 on 2025-10-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0020_appointment_lifecycle_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the patient checked in for the appointment.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="consultation_finished_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the consultation finished.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="consultation_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the consultation started.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentmanagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("rescheduled", "Rescheduled"),
                    ("checked_in", "Checked In"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
