# Generated by Django 5.2.5 on 2025-10-29 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0021_alter_appointmentmanagement_checked_in_at_and_more"),
        ("users", "0013_add_doctor_centric_forms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecordRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of request e.g., full_records, lab_results, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "requested_records",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details about specific records requested",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to email id, file path, or transmission id",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_record_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_requests",
                        to="users.generaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_requests",
                        to="users.nurseprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_record_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record Request",
                "verbose_name_plural": "Medical Record Requests",
                "db_table": "medical_record_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
