# Generated by Django 5.2.5 on 2025-11-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0022_medicalrecordrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurgeAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("PURGE_MEDICAL_RECORDS", "Purge Medical Records")],
                        default="PURGE_MEDICAL_RECORDS",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("patient_profiles_cleared", models.PositiveIntegerField(default=0)),
                ("analytics_records_deleted", models.PositiveIntegerField(default=0)),
                ("assessment_archives_deleted", models.PositiveIntegerField(default=0)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional non-sensitive metadata, e.g., field list, durations",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the purge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purge_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purge_audit_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "status"],
                        name="purge_audit_action_3f2f07_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="purge_audit_started_0640c5_idx"
                    ),
                ],
            },
        ),
    ]
