# Generated by Django 5.2.5 on 2025-10-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_adminuser_email'),
        ('operations', '0022_medicalrecordrequest'),
        ('users', '0013_add_doctor_centric_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Max number of bookings allowed in this slot')),
                ('booked_count', models.PositiveIntegerField(default=0, help_text='Number of bookings confirmed in this slot')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Time Slot',
                'verbose_name_plural': 'Doctor Time Slots',
                'db_table': 'doctor_time_slot',
            },
        ),
        migrations.AddField(
            model_name='appointmentmanagement',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Structured time slot for the appointment (nullable for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='operations.doctortimeslot'),
        ),
        migrations.CreateModel(
            name='HospitalDepartmentDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('capacity_limit', models.PositiveIntegerField(blank=True, help_text='Optional max concurrent appointments for this mapping.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='operations.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='users.generaldoctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_doctors', to='admin_site.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Department Doctor',
                'verbose_name_plural': 'Hospital Department Doctors',
                'db_table': 'hospital_department_doctor',
            },
        ),
        migrations.AddField(
            model_name='doctortimeslot',
            name='hospital_department_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='operations.hospitaldepartmentdoctor'),
        ),
        migrations.AddIndex(
            model_name='hospitaldepartmentdoctor',
            index=models.Index(fields=['hospital', 'department'], name='hospital_de_hospita_cafaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaldepartmentdoctor',
            index=models.Index(fields=['doctor'], name='hospital_de_doctor__7b7c2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitaldepartmentdoctor',
            unique_together={('hospital', 'department', 'doctor')},
        ),
        migrations.AddIndex(
            model_name='doctortimeslot',
            index=models.Index(fields=['hospital_department_doctor', 'date'], name='doctor_time_hospita_53bd91_idx'),
        ),
        migrations.AddIndex(
            model_name='doctortimeslot',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='doctor_time_date_6f9704_idx'),
        ),
        migrations.AddIndex(
            model_name='doctortimeslot',
            index=models.Index(fields=['is_available'], name='doctor_time_is_avai_56d923_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctortimeslot',
            unique_together={('hospital_department_doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
