# Generated by Django 5.2.5 on 2025-10-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_department_doctortimeslot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doctortimeslot',
            name='doctor_time_hospita_53bd91_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctortimeslot',
            name='doctor_time_date_6f9704_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctortimeslot',
            name='doctor_time_is_avai_56d923_idx',
        ),
        migrations.RemoveIndex(
            model_name='hospitaldepartmentdoctor',
            name='hospital_de_hospita_cafaf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='hospitaldepartmentdoctor',
            name='hospital_de_doctor__7b7c2d_idx',
        ),
        migrations.AddField(
            model_name='appointmentmanagement',
            name='department',
            field=models.CharField(default='OPD', help_text='Department for the appointment.', max_length=100),
        ),
    ]
