# Generated by Django 5.2.5 on 2025-11-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_purgeauditlog'),
        ('operations', '0024_remove_doctortimeslot_doctor_time_hospita_53bd91_idx_and_more'),
    ]

    operations = [
    ]
