# Generated by Django 5.2.5 on 2025-11-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_merge_20251107_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordrequest',
            name='clarification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecordrequest',
            name='clarification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecordrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
