# Generated by Django 5.2.5 on 2025-11-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_add_medical_certificate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='clarification_notes',
            field=models.TextField(blank=True, default='', help_text='Notes requesting clarification from patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecordrequest',
            name='request_type',
            field=models.CharField(blank=True, help_text='Type of request e.g., full_records, lab_results, medical_certificate, etc.', max_length=100),
        ),
    ]
