# Generated by Django 4.2.7 on 2025-10-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_remove_patientrecord_is_dummy_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['event_type'], name='analytics_u_event_t_1d438b_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['created_at'], name='analytics_u_created_2d3510_idx'),
        ),
        migrations.CreateModel(
            name='UptimePing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='web', max_length=100)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded')], default='up', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uptime_pings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uptimeping',
            index=models.Index(fields=['service'], name='analytics_u_service_1e4b29_idx'),
        ),
        migrations.AddIndex(
            model_name='uptimeping',
            index=models.Index(fields=['created_at'], name='analytics_u_created_03a32d_idx'),
        ),
    ]