# Generated by Django 5.2.5 on 2025-10-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_usageevent_uptimeping"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="uptimeping",
            new_name="uptime_ping_service_85679e_idx",
            old_name="analytics_u_service_1e4b29_idx",
        ),
        migrations.RenameIndex(
            model_name="uptimeping",
            new_name="uptime_ping_created_4f7654_idx",
            old_name="analytics_u_created_03a32d_idx",
        ),
        migrations.RenameIndex(
            model_name="usageevent",
            new_name="usage_event_event_t_d2d712_idx",
            old_name="analytics_u_event_t_1d438b_idx",
        ),
        migrations.RenameIndex(
            model_name="usageevent",
            new_name="usage_event_created_c1f325_idx",
            old_name="analytics_u_created_2d3510_idx",
        ),
        migrations.AlterField(
            model_name="uptimeping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
