# Generated by Django 5.2.5 on 2025-11-11 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0006_rename_analytics_u_service_1e4b29_idx_uptime_ping_service_85679e_idx_and_more",
        ),
        ("operations", "0025_merge_20251108_0232"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientVolumeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("actual_volume", models.PositiveIntegerField(default=0)),
                (
                    "predicted_volume",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.department",
                    ),
                ),
            ],
            options={
                "db_table": "patient_volume_snapshots",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["resolution", "period_start"],
                        name="patient_vol_resolut_45aa84_idx",
                    ),
                    models.Index(
                        fields=["department", "resolution", "period_start"],
                        name="patient_vol_departm_11a029_idx",
                    ),
                ],
                "unique_together": {("resolution", "period_start", "department")},
            },
        ),
    ]
