# Generated by Django 5.2.5 on 2025-10-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_patientprofile_admission_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hospital_address",
            field=models.TextField(blank=True, help_text="Hospital address"),
        ),
        migrations.AddField(
            model_name="user",
            name="hospital_name",
            field=models.CharField(
                blank=True,
                help_text="Hospital or medical facility name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF, JPG, or PNG file for identity verification",
                null=True,
                upload_to="verification_documents/%Y/%m/%d/",
            ),
        ),
    ]
