# Generated by Django 5.2.5 on 2025-10-08 13:51

import backend.users.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_hospital_address_user_hospital_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (JPG, PNG, or WebP, max 5MB)",
                null=True,
                upload_to=backend.users.image_utils.get_upload_path,
                validators=[backend.users.image_utils.validate_profile_picture],
            ),
        ),
    ]
