# Generated by Django 4.2.7 on 2025-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_update_profile_picture_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable/disable two-factor authentication"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, help_text="Secret key for 2FA", max_length=32, null=True
            ),
        ),
    ]
