# Generated by Django 5.2.5 on 2025-10-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_two_factor_enabled_user_two_factor_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(
                blank=True,
                help_text="Deprecated: optional URL or identifier for profile picture",
                max_length=255,
                null=True,
            ),
        ),
    ]
