# Generated by Django 5.2.5 on 2025-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="discharge_checklist_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Final discharge verification: discharge_vitals, understanding_confirmed, written_instructions_provided, follow_up_appointments_made, equipment_needs, transportation_status, nurse_signature, patient_acknowledgment, discharged_at.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="graphic_flow_sheets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of chronological entries with time_of_reading, repeated_vitals, intake_ml, output_ml, site_checks, and nursing_interventions.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="medication_administration_records",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of medication events: datetime_administered, name, dose, route, nurse_initials, optional prn_reason, prn_response, withheld_reason.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="nursing_intake_assessment",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured intake fields: vitals, anthropometrics, chief complaint, pain score, allergies with reactions, current medications, mental status, fall risk score, assessed_at.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="patient_education_record",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of education interactions: topics, teaching_method, comprehension_level, return_demonstration, barriers_to_learning, recorded_at.",
            ),
        ),
    ]
