# Generated by Django 5.2.5 on 2025-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_patientprofile_discharge_checklist_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="history_physical_forms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of H&P forms: patient_name, dob, mrn, provider_signature, provider_id, chief_complaint, history_present_illness, past_medical_history, social_history, review_of_systems, physical_exam, assessment, diagnoses_icd_codes, initial_plan, created_at.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="operative_procedure_reports",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of operative/procedure reports: patient_id, date_time_performed, procedure_name, indications, consent_status, anesthesia_type, anesthesia_dose, procedure_steps, findings, complications, disposition_plan, surgeon_provider_signature, created_at.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="progress_notes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of SOAP progress notes: date_time_note, subjective, objective, vitals, lab_imaging_results, assessment, plan, follow_up_date, provider_signature, created_at.",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="provider_order_sheets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of provider orders: ordering_provider, date_time_placed, order_type, medication_orders (drug_name, dose, route, frequency), diagnostic_orders (test_name, priority, reason), consultation_orders (specialty, question), general_orders, order_status, created_at.",
            ),
        ),
    ]
