# Generated by Django 5.2.5 on 2025-10-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_adminuser_email'),
        ('users', '0013_add_doctor_centric_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='hospital_fk',
            field=models.ForeignKey(blank=True, help_text='Structured hospital reference (nullable for backward compatibility).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='admin_site.hospital'),
        ),
    ]
