# Generated by Django 5.2.5 on 2025-10-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_patientprofile_hospital_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='hospital_fk',
        ),
    ]
